import styles from "./page.module.css";
import TokenFeed from "@/components/TokenFeed";
import { Token, TwitterSentiment, TelegramSentiment } from "@/types/token.types";

// Sample token data
const sampleTokens: Token[] = [
	{
		id: "1",
		name: "Bitcoin",
		ticker: "BTC",
		marketCap: 1_250_000_000_000,
		price: 65432.1,
		change24h: 2.34,
		imageUrl: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
		liquidity: 25_000_000_000,
		volume: 32_500_000_000,
		callers: [
			{
				id: "c1",
				name: "Alex Johnson",
				profileImageUrl: "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				lastCallTimestamp: Date.now() - 3600000,
				callCount: 42,
				winRate: 78,
				message: "This token has strong fundamentals and shows promising growth potential. I'm bullish on BTC for the long term.",
			},
			{
				id: "c2",
				name: "Maria Garcia",
				profileImageUrl: "https://www.gravatar.com/avatar/3b3be63a4c2a439b013787725dfce802?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 10,
				lastCallTimestamp: Date.now() - 3600000 * 2,
				callCount: 28,
				winRate: 65,
				message: "Bitcoin's recent price action suggests we're entering a new accumulation phase. The technical indicators are aligning for a move up.",
			},
			{
				id: "c3",
				name: "Wei Zhang",
				profileImageUrl: "https://www.gravatar.com/avatar/f9879d71855b5ff21e4963273a886bfc?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 2,
				lastCallTimestamp: Date.now() - 3600000 * 5,
				callCount: 15,
				winRate: 42,
				message: "I'm seeing a potential breakout pattern forming. The recent consolidation around support levels is promising.",
			},
			{
				id: "c4",
				name: "Jamal Williams",
				profileImageUrl: "https://www.gravatar.com/avatar/a5a271f9eee8bbb3795f41665a817f76?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 4,
				callCount: 8,
				winRate: 33,
				message: "Despite recent volatility, Bitcoin remains the cornerstone of crypto. The upcoming halving event should catalyze the next bull run.",
			},
			{
				id: "c5",
				name: "Sophie Martin",
				profileImageUrl: "https://www.gravatar.com/avatar/9e7b59baff875e6a2e79a8563e3dc7d4?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				callCount: 12,
				winRate: 58,
				message: "Institutional adoption continues to grow. With major banks now offering Bitcoin services, we're seeing the beginning of mainstream acceptance.",
			},
			{
				id: "c6",
				name: "Raj Patel",
				profileImageUrl: "https://www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058?s=200&d=identicon",
				timestamp: Date.now() - (3600000 * 24 * 3 + 3600000 * 5 + 60000 * 23 + 1000 * 17),
				callCount: 5,
				winRate: 20,
			},
			{
				id: "c7",
				name: "Emma Wilson",
				profileImageUrl: "https://www.gravatar.com/avatar/7a4e3461b1c25e5000e2c9220e6a9913?s=200&d=identicon",
				timestamp: Date.now() - (3600000 * 24 * 8 + 3600000 * 2 + 60000 * 45 + 1000 * 33),
				callCount: 14,
				winRate: 71,
				message: "Bitcoin's correlation with traditional markets is decreasing, reinforcing its value as a hedge against inflation and economic uncertainty.",
			},
			{
				id: "c8",
				name: "Carlos Rodriguez",
				profileImageUrl: "https://www.gravatar.com/avatar/6a6c19fea4a3676970167ce51f39e6ee?s=200&d=identicon",
				timestamp: Date.now() - (3600000 * 24 * 1 + 3600000 * 7 + 60000 * 12 + 1000 * 51),
				callCount: 3,
				winRate: 67,
				message: "The on-chain metrics are showing strong accumulation by long-term holders. This typically precedes significant price movements.",
			},
		],
		createdAt: "2009-01-03T18:15:05Z",
		twitterSentiment: {
			summary: "Strong bullish sentiment with 78% positive tweets. Recent discussions focus on institutional adoption and the upcoming halving event. Notable increase in whale activity and accumulation patterns.",
			sentiment: "positive",
			count: 2847,
			positiveSplit: 78,
			negativeSplit: 22,
		} as TwitterSentiment,
		telegramSentiment: {
			summary: "Extremely bullish sentiment in Telegram groups with active discussions about Bitcoin's price action. Institutional adoption and upcoming halving dominate conversations.",
			sentiment: "positive",
			count: 3256,
			positiveSplit: 82,
			negativeSplit: 18,
		} as TelegramSentiment,
	},
	{
		id: "2",
		name: "Ethereum",
		ticker: "ETH",
		marketCap: 345_000_000_000,
		price: 3456.78,
		change24h: -1.23,
		imageUrl: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
		liquidity: 12_500_000_000,
		volume: 18_700_000_000,
		callers: [
			{
				id: "c9",
				name: "Olivia Brown",
				profileImageUrl: "https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				lastCallTimestamp: Date.now() - 3600000 * 6,
				callCount: 37,
				winRate: 62,
				message: "Ethereum's upcoming protocol upgrade should drive significant value. I'm expecting a 20% price increase within the next month.",
			},
			{
				id: "c10",
				name: "Liam Davis",
				profileImageUrl: "https://www.gravatar.com/avatar/8eb1b522f60d11fa897de1dc6351b7e8?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 7,
				lastCallTimestamp: Date.now() - 3600000 * 12,
				callCount: 19,
				winRate: 51,
				message: "Ethereum's shift to proof-of-stake has dramatically reduced its energy consumption. This environmental advantage will drive further adoption.",
			},
			{
				id: "c11",
				name: "Aisha Khan",
				profileImageUrl: "https://www.gravatar.com/avatar/6d8ebb117e8d83d74ea95fbdd0f87e13?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				winRate: 45,
				callCount: 23,
				message: "Layer 2 solutions are finally solving Ethereum's scaling issues. As transaction costs decrease, we'll see a new wave of dApp adoption.",
			},
			{
				id: "c12",
				name: "Noah Miller",
				profileImageUrl: "https://www.gravatar.com/avatar/cb7a03c62e5a75f3af9a8c0c3e2179b3?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 9,
				winRate: 38,
				callCount: 11,
				message: "ETH's deflationary mechanism through EIP-1559 is starting to show effects. With reduced issuance post-merge, supply pressure is mounting.",
			},
			{
				id: "c13",
				name: "Isabella Lopez",
				profileImageUrl: "https://www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				winRate: 55,
				callCount: 17,
				message: "Ethereum remains the primary platform for DeFi and NFTs. Its first-mover advantage and developer ecosystem are unmatched.",
			},
			{
				id: "c14",
				name: "Ethan Taylor",
				profileImageUrl: "https://www.gravatar.com/avatar/7a4e3461b1c25e5000e2c9220e6a9913?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				winRate: 63,
				callCount: 29,
				message: "The upcoming Shanghai upgrade will enable staking withdrawals, removing a major concern for institutional investors considering ETH.",
			},
		],
		createdAt: "2015-07-30T15:26:28Z",
		twitterSentiment: {
			summary: "Mixed sentiment with growing optimism around Layer 2 scaling solutions. Community discussions highlight reduced gas fees and increased DeFi activity. Technical analysis suggests consolidation phase.",
			sentiment: "neutral",
			count: 1923,
			positiveSplit: 52,
			negativeSplit: 48,
		} as TwitterSentiment,
		telegramSentiment: {
			summary: "Active technical discussions about Layer 2 solutions and upcoming protocol upgrades. Community sentiment remains optimistic despite recent price action.",
			sentiment: "positive",
			count: 2845,
			positiveSplit: 65,
			negativeSplit: 35,
		} as TelegramSentiment,
	},
	{
		id: "3",
		name: "Solana",
		ticker: "SOL",
		marketCap: 45_000_000_000,
		price: 123.45,
		change24h: 5.67,
		imageUrl: "https://cryptologos.cc/logos/solana-sol-logo.png",
		liquidity: 10_000_000_000,
		volume: 12_300_000_000,
		callers: [
			{
				id: "c15",
				name: "Michael Lee",
				profileImageUrl: "https://www.gravatar.com/avatar/a2d6b94b5de9113071931d5c43b2ea4d?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 2,
				winRate: 72,
				callCount: 31,
				message: "Solana's transaction throughput continues to impress. With new dApps launching weekly, I expect sustained growth.",
			},
			{
				id: "c16",
				name: "Emily Chen",
				profileImageUrl: "https://www.gravatar.com/avatar/5c42d3e28ad3d5b4ca3db3f5c3537d49?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 4,
				winRate: 59,
				callCount: 22,
				message: "Solana's ecosystem is growing rapidly despite recent network challenges. The focus on mobile and consumer applications sets it apart.",
			},
			{
				id: "c17",
				name: "Daniel Kim",
				profileImageUrl: "https://www.gravatar.com/avatar/9e1f8db0b3fda3445d7b9b9c4f2cb7f0?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 7,
				winRate: 48,
				callCount: 15,
				message: "Recent stability improvements have addressed Solana's biggest weakness. With high throughput and low fees, it's positioned for growth.",
			},
			{
				id: "c18",
				name: "Sophia Patel",
				profileImageUrl: "https://www.gravatar.com/avatar/0c83f57c786a0b4a39efab23731c7ebc?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				winRate: 67,
				callCount: 27,
				message: "Solana's NFT marketplace is gaining traction with lower fees than Ethereum. This could be a major growth driver in the coming months.",
			},
			{
				id: "c19",
				name: "James Rodriguez",
				profileImageUrl: "https://www.gravatar.com/avatar/f0e9e11e56c1cb6e6f13bc99d576b77a?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				winRate: 53,
				callCount: 19,
				message: "The Solana Mobile Stack and Saga phone represent a unique approach to crypto adoption. This focus on user experience could be transformative.",
			},
		],
		createdAt: "2020-03-16T14:22:47Z",
		twitterSentiment: {
			summary: "Bearish sentiment prevails with concerns about network stability. Critics highlight recent outages, while supporters emphasize growing developer activity. Trading volume shows distribution patterns.",
			sentiment: "negative",
			count: 1245,
			positiveSplit: 35,
			negativeSplit: 65,
		} as TwitterSentiment,
		telegramSentiment: {
			summary: "Mixed reactions to recent network performance improvements. Developer activity and new project launches maintain community interest despite concerns.",
			sentiment: "neutral",
			count: 1567,
			positiveSplit: 48,
			negativeSplit: 52,
		} as TelegramSentiment,
	},
	{
		id: "4",
		name: "Cardano",
		ticker: "ADA",
		marketCap: 15_000_000_000,
		price: 0.45,
		change24h: -0.89,
		imageUrl: "https://cryptologos.cc/logos/cardano-ada-logo.png",
		liquidity: 5_000_000_000,
		volume: 3_800_000_000,
		callers: [
			{
				id: "c35",
				name: "Thomas Wilson",
				profileImageUrl: "https://www.gravatar.com/avatar/b48def645758b95537d4424c84d1a9ff?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				winRate: 64,
				callCount: 25,
				message: "Cardano's methodical, research-first approach is finally bearing fruit with smart contract functionality. The ecosystem is poised for growth.",
			},
			{
				id: "c36",
				name: "Hannah Lee",
				profileImageUrl: "https://www.gravatar.com/avatar/5496f32b92e0f6933d1ed0f5971996ee?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				winRate: 58,
				callCount: 19,
				message: "ADA's staking mechanism provides sustainable yield without the risks associated with lending. This security-focused approach has merit.",
			},
		],
		createdAt: "2017-09-29T11:45:23Z",
		telegramSentiment: {
			summary: "Steady optimism around development progress and academic approach. Community emphasizes long-term potential over short-term price action.",
			sentiment: "positive",
			count: 892,
			positiveSplit: 71,
			negativeSplit: 29,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Neutral sentiment with focus on academic approach and Africa initiatives. Development progress generates interest despite price consolidation.",
			sentiment: "neutral",
			count: 1234,
			positiveSplit: 55,
			negativeSplit: 45,
		} as TwitterSentiment,
	},
	{
		id: "5",
		name: "Polkadot",
		ticker: "DOT",
		marketCap: 8_500_000_000,
		price: 7.89,
		change24h: 3.21,
		imageUrl: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
		liquidity: 2_000_000_000,
		volume: 2_500_000_000,
		callers: [
			{
				id: "c20",
				name: "Ava Martinez",
				profileImageUrl: "https://www.gravatar.com/avatar/9e1f8db0b3fda3445d7b9b9c4f2cb7f0?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				winRate: 61,
				callCount: 23,
				message: "Polkadot's interoperability focus addresses a critical need in the blockchain ecosystem. As parachains mature, DOT will capture more value.",
			},
			{
				id: "c21",
				name: "Ethan Thompson",
				profileImageUrl: "https://www.gravatar.com/avatar/0c83f57c786a0b4a39efab23731c7ebc?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 8,
				winRate: 44,
				callCount: 18,
				message: "The shared security model of Polkadot provides significant advantages for new blockchains. This innovation is underappreciated by the market.",
			},
			{
				id: "c22",
				name: "Mia Rodriguez",
				profileImageUrl: "https://www.gravatar.com/avatar/6a6c19fea4a3676970167ce51f39e6ee?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 4,
				winRate: 72,
				callCount: 25,
				message: "Polkadot's parachain ecosystem is finally gaining traction. This is a long-term hold with significant upside potential.",
			},
			{
				id: "c23",
				name: "Noah Hernandez",
				profileImageUrl: "https://www.gravatar.com/avatar/c9cddb28f2731055cbd88a1e7d4a8156?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 2,
				winRate: 39,
				callCount: 13,
				message: "Polkadot's governance mechanism is one of the most sophisticated in crypto. This will enable it to evolve more effectively than competitors.",
			},
		],
		createdAt: "2020-05-26T09:33:51Z",
		telegramSentiment: {
			summary: "Growing excitement about parachain ecosystem development. Technical discussions dominate with focus on cross-chain capabilities.",
			sentiment: "positive",
			count: 743,
			positiveSplit: 68,
			negativeSplit: 32,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Positive sentiment around parachain auctions and ecosystem growth. Technical discussions highlight cross-chain interoperability advantages.",
			sentiment: "positive",
			count: 856,
			positiveSplit: 72,
			negativeSplit: 28,
		} as TwitterSentiment,
	},
	{
		id: "6",
		name: "Avalanche",
		ticker: "AVAX",
		marketCap: 12_300_000_000,
		price: 35.67,
		change24h: 4.56,
		imageUrl: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
		liquidity: 3_000_000_000,
		volume: 4_200_000_000,
		callers: [
			{
				id: "c24",
				name: "Liam Davis",
				profileImageUrl: "https://www.gravatar.com/avatar/b48def645758b95537d4424c84d1a9ff?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				winRate: 58,
				callCount: 21,
				message: "Avalanche's three-chain architecture offers unique advantages for different use cases. The C-Chain's EVM compatibility has driven rapid adoption.",
			},
			{
				id: "c25",
				name: "Emily Chen",
				profileImageUrl: "https://www.gravatar.com/avatar/5496f32b92e0f6933d1ed0f5971996ee?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				winRate: 66,
				callCount: 29,
				message: "Avalanche is positioning itself as a serious Ethereum competitor. Their subnet technology offers unique scaling advantages.",
			},
			{
				id: "c26",
				name: "Sophia Patel",
				profileImageUrl: "https://www.gravatar.com/avatar/f0e9e11e56c1cb6e6f13bc99d576b77a?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 7,
				winRate: 47,
				callCount: 16,
				message: "Avalanche's partnership strategy with traditional finance and gaming companies is opening new markets. This institutional approach is promising.",
			},
		],
		createdAt: "2020-09-21T16:38:12Z",
		telegramSentiment: {
			summary: "Strong developer engagement and institutional partnership discussions. Community shows confidence in subnet technology adoption.",
			sentiment: "positive",
			count: 612,
			positiveSplit: 73,
			negativeSplit: 27,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Bullish sentiment driven by subnet adoption and institutional partnerships. Community highlights scaling advantages and EVM compatibility.",
			sentiment: "positive",
			count: 967,
			positiveSplit: 69,
			negativeSplit: 31,
		} as TwitterSentiment,
	},
	{
		id: "7",
		name: "Chainlink",
		ticker: "LINK",
		marketCap: 7_800_000_000,
		price: 14.32,
		change24h: -2.15,
		imageUrl: "https://cryptologos.cc/logos/chainlink-link-logo.png",
		liquidity: 1_500_000_000,
		volume: 1_900_000_000,
		callers: [
			{
				id: "c27",
				name: "Olivia Brown",
				profileImageUrl: "https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 4,
				winRate: 73,
				callCount: 32,
				message: "Chainlink's oracle services are becoming the industry standard. As DeFi grows, LINK will continue to capture value.",
			},
			{
				id: "c28",
				name: "Liam Davis",
				profileImageUrl: "https://www.gravatar.com/avatar/8eb1b522f60d11fa897de1dc6351b7e8?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				winRate: 51,
				callCount: 19,
			},
		],
		createdAt: "2017-09-18T10:12:33Z",
		telegramSentiment: {
			summary: "Technical discussions about oracle network expansion and new partnerships. Community sentiment reflects confidence in fundamental value.",
			sentiment: "neutral",
			count: 534,
			positiveSplit: 55,
			negativeSplit: 45,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Strong positive sentiment around oracle network expansion. New partnerships and DeFi integration drive community confidence.",
			sentiment: "positive",
			count: 789,
			positiveSplit: 75,
			negativeSplit: 25,
		} as TwitterSentiment,
	},
	{
		id: "8",
		name: "Polygon",
		ticker: "MATIC",
		marketCap: 9_200_000_000,
		price: 0.98,
		change24h: 1.45,
		imageUrl: "https://cryptologos.cc/logos/polygon-matic-logo.png",
		liquidity: 2_000_000_000,
		volume: 2_800_000_000,
		callers: [
			{
				id: "c29",
				name: "Ava Martinez",
				profileImageUrl: "https://www.gravatar.com/avatar/6d8ebb117e8d83d74ea95fbdd0f87e13?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 3,
				winRate: 64,
				callCount: 24,
				message: "Polygon's multi-solution approach to Ethereum scaling gives it versatility. The zkEVM rollup is particularly promising for future growth.",
			},
			{
				id: "c37",
				name: "Jason Kim",
				profileImageUrl: "https://www.gravatar.com/avatar/a2d6b94b5de9113071931d5c43b2ea4d?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				winRate: 59,
				callCount: 22,
				message: "Polygon's strategic acquisitions in the zero-knowledge space position it well for the future of Ethereum scaling. The technology moat is widening.",
			},
		],
		createdAt: "2019-04-22T08:45:19Z",
		telegramSentiment: {
			summary: "Enthusiastic discussions about zkEVM rollup and scaling solutions. Developer activity and enterprise adoption drive positive sentiment.",
			sentiment: "positive",
			count: 923,
			positiveSplit: 76,
			negativeSplit: 24,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Bullish discussions around zkEVM technology and scaling solutions. Enterprise adoption and developer activity maintain positive momentum.",
			sentiment: "positive",
			count: 1432,
			positiveSplit: 78,
			negativeSplit: 22,
		} as TwitterSentiment,
	},
	{
		id: "9",
		name: "Uniswap",
		ticker: "UNI",
		marketCap: 5_400_000_000,
		price: 7.21,
		change24h: 0.78,
		imageUrl: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
		liquidity: 1_000_000_000,
		volume: 3_500_000_000,
		callers: [
			{
				id: "c30",
				name: "Maria Garcia",
				profileImageUrl: "https://www.gravatar.com/avatar/cb7a03c62e5a75f3af9a8c0c3e2179b3?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 5,
				winRate: 57,
				callCount: 22,
				message: "Uniswap's dominance in DEX volume continues despite increasing competition. The brand recognition and liquidity are significant advantages.",
			},
			{
				id: "c31",
				name: "Raj Patel",
				profileImageUrl: "https://www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 7,
				winRate: 43,
				callCount: 17,
				message: "The UNI token's governance rights are becoming more valuable as the protocol's fee switch discussions advance. This could be a catalyst for price action.",
			},
			{
				id: "c32",
				name: "Ethan Taylor",
				profileImageUrl: "https://www.gravatar.com/avatar/7a4e3461b1c25e5000e2c9220e6a9913?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 2,
				winRate: 69,
				callCount: 26,
				message: "Uniswap v3's concentrated liquidity is a game-changer. The protocol's fee generation makes it undervalued at current prices.",
			},
		],
		createdAt: "2020-09-17T13:24:56Z",
		telegramSentiment: {
			summary: "Active debates about governance proposals and fee switch implementation. Trading volume metrics maintain community confidence.",
			sentiment: "neutral",
			count: 445,
			positiveSplit: 52,
			negativeSplit: 48,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Mixed sentiment with focus on governance proposals and fee switch discussions. Trading volumes and market share maintain community interest.",
			sentiment: "neutral",
			count: 678,
			positiveSplit: 54,
			negativeSplit: 46,
		} as TwitterSentiment,
	},
	{
		id: "10",
		name: "Dogecoin",
		ticker: "DOGE",
		marketCap: 14_500_000_000,
		price: 0.105,
		change24h: 3.45,
		imageUrl: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
		liquidity: 5_000_000_000,
		volume: 7_200_000_000,
		callers: [
			{
				id: "c33",
				name: "Sophia Patel",
				profileImageUrl: "https://www.gravatar.com/avatar/a2d6b94b5de9113071931d5c43b2ea4d?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 4,
				winRate: 62,
				callCount: 23,
				message: "Dogecoin's cultural relevance gives it staying power beyond technical fundamentals. The community's enthusiasm creates unique market dynamics.",
			},
			{
				id: "c34",
				name: "Emily Chen",
				profileImageUrl: "https://www.gravatar.com/avatar/5c42d3e28ad3d5b4ca3db3f5c3537d49?s=200&d=identicon",
				timestamp: Date.now() - 3600000 * 24 * 6,
				winRate: 55,
				callCount: 20,
				message: "Recent development activity on Dogecoin is adding utility to what was once just a meme coin. The potential for smart contracts could be transformative.",
			},
		],
		createdAt: "2013-12-06T22:31:48Z",
		telegramSentiment: {
			summary: "Meme-driven enthusiasm with increased discussion about utility development. Community remains highly engaged despite market volatility.",
			sentiment: "positive",
			count: 1876,
			positiveSplit: 69,
			negativeSplit: 31,
		} as TelegramSentiment,
		twitterSentiment: {
			summary: "Highly volatile sentiment driven by social media trends and celebrity mentions. Community remains active despite market fluctuations.",
			sentiment: "neutral",
			count: 2345,
			positiveSplit: 58,
			negativeSplit: 42,
		} as TwitterSentiment,
	},
];

export default function Home() {
	return (
		<div className={styles.page}>
			<TokenFeed tokens={sampleTokens} />
		</div>
	);
}
