services:
  - type: web
    name: telegram-middleware
    runtime: docker
    region: oregon
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
    disk:
      name: telegram-sessions
      mountPath: /app/sessions
      sizeGB: 1
    autoDeploy: true
    healthCheck:
      path: /api/health
      interval: 30s
      timeout: 10s
      gracePeriod: 300s
    scaling:
      minInstances: 1
      maxInstances: 1
    domains:
      - telegram-middleware.yourdomain.com # Replace with your domain 