name: Deploy Chat Scraper to ECS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Repository (with submodules)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./backend-private
        run: npm install

      - name: Run Tests
        working-directory: ./backend-private
        run: npm test -- --passWithNoTests

      - name: Build Docker Images
        working-directory: ./backend-private/docker
        run: |
          # Set environment variable to avoid Prisma symlinks
          export PRISMA_GENERATE_SKIP_AUTOINSTALL=true
          
          # First build the base image
          echo "Building base image..."
          docker build -t kifi-base:latest -f Dockerfile.base ..
          
          # Then build the chat-scraper image
          echo "Building chat-scraper image..."
          docker build -t ${{ secrets.SCRAPER_ECR_REPOSITORY }}/chat-scraper:${{ github.sha }} -f Dockerfile.chat-scraper ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.SCRAPER_ECR_REPOSITORY }}/chat-scraper:${{ github.sha }}

      - name: Set image tag output
        id: set-tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update ECS Task Definition and Service
        id: ecs-update
        run: |
          CURRENT_TASK_DEF=$(aws ecs describe-task-definition --task-definition "${{ secrets.CHAT_SCRAPER_TASK_DEFINITION }}" --query 'taskDefinition' --output json)
          echo "Image tag from build: ${{ needs.build.outputs.image_tag }}"
          NEW_TASK_DEF=$(echo "$CURRENT_TASK_DEF" | jq --arg IMAGE "${{ secrets.SCRAPER_ECR_REPOSITORY }}/chat-scraper:${{ needs.build.outputs.image_tag }}" '.containerDefinitions[0].image = $IMAGE')          
          CLEAN_TASK_DEF=$(echo "$NEW_TASK_DEF" | jq 'del(.status, .revision, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
          echo "Registering new task definition..."
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json "$CLEAN_TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"
          echo "Updating ECS service..."
          aws ecs update-service --cluster "${{ secrets.ECS_CLUSTER }}" --service "${{ secrets.CHAT_SCRAPER_SERVICE }}" --task-definition "$NEW_TASK_DEF_ARN"
          
      - name: Wait for Service Stability
        run: |
          echo "Waiting for ECS service to stabilize..."
          aws ecs wait services-stable --cluster "${{ secrets.ECS_CLUSTER }}" --services "${{ secrets.CHAT_SCRAPER_SERVICE }}" 