name: Deploy Frontend to ECS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Docker Image
        working-directory: ./frontend
        run: |
          docker build --build-arg NEXT_PUBLIC_PRIVY_ID=${{ secrets.PRIVY_ID }} -t ${{ secrets.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }}

      - name: Set image tag output
        id: set-tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update ECS Task Definition and Service
        id: ecs-update
        run: |
          CURRENT_TASK_DEF=$(aws ecs describe-task-definition --task-definition "${{ secrets.FRONTEND_TASK_DEFINITION }}" --query 'taskDefinition' --output json)
          echo "Image tag from build: ${{ needs.build.outputs.image_tag }}"
          NEW_TASK_DEF=$(echo "$CURRENT_TASK_DEF" | jq --arg IMAGE "${{ secrets.FRONTEND_ECR_REPOSITORY }}:${{ needs.build.outputs.image_tag }}" '.containerDefinitions[0].image = $IMAGE')          
          CLEAN_TASK_DEF=$(echo "$NEW_TASK_DEF" | jq 'del(.status, .revision, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
          echo "Registering new task definition..."
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json "$CLEAN_TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"
          echo "Updating ECS service..."
          aws ecs update-service --cluster "${{ secrets.ECS_CLUSTER }}" --service "${{ secrets.FRONTEND_SERVICE }}" --task-definition "$NEW_TASK_DEF_ARN"
          
      - name: Wait for Service Stability
        run: |
          echo "Waiting for ECS service to stabilize..."
          aws ecs wait services-stable --cluster "${{ secrets.ECS_CLUSTER }}" --services "${{ secrets.FRONTEND_SERVICE }}" 