-- AlterTable
ALTER TABLE "User" 
  ADD COLUMN IF NOT EXISTS "enableAutoAlpha" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "selectedChatsIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "groupCallThreshold" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "slippage" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
  ADD COLUMN IF NOT EXISTS "buyAmount" DOUBLE PRECISION NOT NULL DEFAULT 0.05; 